from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .reports import OpsReportsView
from .views import (
    AgentAPIView,
    AccountSummaryAPIView,
    AboutPageView,
    BusinessPageView,
    DataDeletionCallbackView,
    BookingInquiryCreateView,
    CalendarOpsView,
    CustomerDashboardView,
    DataDeletionPageView,
    DamageDepositCheckoutView,
    DamageDepositSuccessView,
    DonationCheckoutView,
    DonationSuccessView,
    HomePageView,
    InvoicePrintView,
    LegacyOpsDashboardView,
    ModernAccountView,
    ModernSiteView,
    ModernOpsDashboardView,
    OpsReservationsView,
    OpsSummaryAPIView,
    OAuthDiagnosticsView,
    PayPalDamageDepositCancelView,
    PayPalDamageDepositSuccessView,
    PrivacyPolicyPageView,
    PublicSiteSummaryAPIView,
    ReservationCancelView,
    ReservationDetailView,
    ReservationUpdateView,
    ModernReservationCancelView,
    ModernReservationDetailView,
    ModernReservationUpdateView,
    SignUpView,
    StayDetailView,
    StripeWebhookView,
    TermsPageView,
)


app_name = "bookings"

urlpatterns = [
    path("", ModernSiteView.as_view(), name="home"),
    path("legacy-home/", HomePageView.as_view(), name="legacy-home"),
    path("about/", ModernSiteView.as_view(), name="about"),
    path("legacy-about/", AboutPageView.as_view(), name="legacy-about"),
    path("business/", ModernSiteView.as_view(), name="business"),
    path("legacy-business/", BusinessPageView.as_view(), name="legacy-business"),
    path("privacy/", ModernSiteView.as_view(), name="privacy-policy"),
    path("legacy-privacy/", PrivacyPolicyPageView.as_view(), name="legacy-privacy-policy"),
    path("terms/", ModernSiteView.as_view(), name="terms"),
    path("legacy-terms/", TermsPageView.as_view(), name="legacy-terms"),
    path("data-deletion/", ModernSiteView.as_view(), name="data-deletion"),
    path("legacy-data-deletion/", DataDeletionPageView.as_view(), name="legacy-data-deletion"),
    path("data-deletion/callback/", DataDeletionCallbackView.as_view(), name="data-deletion-callback"),
    path("accounts/signup/", SignUpView.as_view(), name="signup"),
    path("accounts/login/", LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/", ModernAccountView.as_view(), name="dashboard"),
    path("legacy-accounts/", CustomerDashboardView.as_view(), name="legacy-dashboard"),
    path("accounts/reservations/<int:pk>/", ModernReservationDetailView.as_view(), name="reservation-detail"),
    path("accounts/reservations/<int:pk>/edit/", ModernReservationUpdateView.as_view(), name="reservation-edit"),
    path("accounts/reservations/<int:pk>/cancel/", ModernReservationCancelView.as_view(), name="reservation-cancel"),
    path("legacy-accounts/reservations/<int:pk>/", ReservationDetailView.as_view(), name="legacy-reservation-detail"),
    path("legacy-accounts/reservations/<int:pk>/edit/", ReservationUpdateView.as_view(), name="legacy-reservation-edit"),
    path("legacy-accounts/reservations/<int:pk>/cancel/", ReservationCancelView.as_view(), name="legacy-reservation-cancel"),
    path("stays/<slug:slug>/", ModernSiteView.as_view(), name="stay-detail"),
    path("legacy-stays/<slug:slug>/", StayDetailView.as_view(), name="legacy-stay-detail"),
    path("inquiries/", BookingInquiryCreateView.as_view(), name="inquiry-create"),
    path("invoices/<uuid:token>/", InvoicePrintView.as_view(), name="invoice-print"),
    path("deposits/checkout/", DamageDepositCheckoutView.as_view(), name="deposit-checkout"),
    path("deposits/success/", DamageDepositSuccessView.as_view(), name="deposit-success"),
    path("deposits/paypal/success/", PayPalDamageDepositSuccessView.as_view(), name="deposit-paypal-success"),
    path("deposits/paypal/cancel/", PayPalDamageDepositCancelView.as_view(), name="deposit-paypal-cancel"),
    path("donations/checkout/", DonationCheckoutView.as_view(), name="donation-checkout"),
    path("donations/success/", DonationSuccessView.as_view(), name="donation-success"),
    path("ops/dashboard/", ModernOpsDashboardView.as_view(), name="ops-dashboard"),
    path("ops/legacy-dashboard/", LegacyOpsDashboardView.as_view(), name="ops-legacy-dashboard"),
    path("ops/reservations/", OpsReservationsView.as_view(), name="ops-reservations"),
    path("ops/reports/", OpsReportsView.as_view(), name="ops-reports"),
    path("ops/calendar/", CalendarOpsView.as_view(), name="calendar-ops"),
    path("ops/oauth/", OAuthDiagnosticsView.as_view(), name="oauth-diagnostics"),
    path("stripe/webhook/", StripeWebhookView.as_view(), name="stripe-webhook"),
    path("api/agent/", AgentAPIView.as_view(), name="agent-api"),
    path("api/account/summary/", AccountSummaryAPIView.as_view(), name="account-summary-api"),
    path("api/site/summary/", PublicSiteSummaryAPIView.as_view(), name="site-summary-api"),
    path("api/ops/summary/", OpsSummaryAPIView.as_view(), name="ops-summary-api"),
]
