from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import RedirectView

from .forms import MLADISAuthenticationForm
from .reports import ModernOpsReportsView, OpsReportsAPIView
from .views import (
    AgentAPIView,
    AccountSummaryAPIView,
    ChatKitSessionAPIView,
    DataDeletionCallbackView,
    BookingInquiryCreateView,
    CombinedPaymentCheckoutView,
    CombinedPaymentSuccessView,
    DamageDepositCheckoutView,
    DamageDepositSuccessView,
    DonationCheckoutView,
    DonationSuccessView,
    InvoicePrintView,
    ModernAccountView,
    ModernSiteView,
    ModernOpsDashboardView,
    ModernOpsAgentView,
    ModernOpsCalendarView,
    ModernOpsCustomersView,
    ModernOpsPaymentsView,
    ModernOpsDepositsView,
    ModernOpsMaintenanceView,
    ModernOpsReservationsView,
    ModernOpsStaysView,
    OpsAgentAPIView,
    OpsCalendarAPIView,
    OpsCalendarBlockAPIView,
    OpsCalendarPriceAPIView,
    OpsCustomersAPIView,
    OpsDepositsAPIView,
    OpsMaintenanceAIDescriptionAPIView,
    OpsMaintenanceAgentPayloadAPIView,
    OpsMaintenanceAPIView,
    OpsMaintenanceDraftAIDescriptionAPIView,
    OpsReservationsAPIView,
    OpsReservationStatusAPIView,
    OpsSummaryAPIView,
    PayPalDamageDepositCancelView,
    PayPalDamageDepositSuccessView,
    PaymentConfirmationView,
    PolicyDocumentView,
    PublicSiteSummaryAPIView,
    ReservationPaymentCheckoutView,
    ReservationPaymentContextAPIView,
    ReservationPaymentSuccessView,
    ModernReservationCancelView,
    ModernReservationDetailView,
    ModernReservationUpdateView,
    OAuthDiagnosticsView,
    SignUpView,
    SocialProviderLaunchView,
    StripeWebhookView,
)


app_name = "bookings"

urlpatterns = [
    path("", ModernSiteView.as_view(), name="home"),
    path("legacy-home/", RedirectView.as_view(pattern_name="bookings:home", permanent=False), name="legacy-home"),
    path("about/", ModernSiteView.as_view(), name="about"),
    path("legacy-about/", RedirectView.as_view(pattern_name="bookings:about", permanent=False), name="legacy-about"),
    path("business/", ModernSiteView.as_view(), name="business"),
    path("legacy-business/", RedirectView.as_view(pattern_name="bookings:business", permanent=False), name="legacy-business"),
    path("privacy/", ModernSiteView.as_view(), name="privacy-policy"),
    path("legacy-privacy/", RedirectView.as_view(pattern_name="bookings:privacy-policy", permanent=False), name="legacy-privacy-policy"),
    path("terms/", ModernSiteView.as_view(), name="terms"),
    path("legacy-terms/", RedirectView.as_view(pattern_name="bookings:terms", permanent=False), name="legacy-terms"),
    path("data-deletion/", ModernSiteView.as_view(), name="data-deletion"),
    path("legacy-data-deletion/", RedirectView.as_view(pattern_name="bookings:data-deletion", permanent=False), name="legacy-data-deletion"),
    path("data-deletion/callback/", DataDeletionCallbackView.as_view(), name="data-deletion-callback"),
    path(
        "property-rules/",
        PolicyDocumentView.as_view(document_kind="property_rules"),
        name="property-rules",
    ),
    path(
        "damage-deposit-terms/",
        PolicyDocumentView.as_view(document_kind="damage_terms"),
        name="damage-deposit-terms",
    ),
    path("accounts/signup/", SignUpView.as_view(), name="signup"),
    path("accounts/login/", LoginView.as_view(authentication_form=MLADISAuthenticationForm, template_name="registration/login.html"), name="login"),
    path("accounts/social/<slug:provider_id>/", SocialProviderLaunchView.as_view(), name="social-provider-launch"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("accounts/", ModernAccountView.as_view(), name="dashboard"),
    path("legacy-accounts/", RedirectView.as_view(pattern_name="bookings:dashboard", permanent=False), name="legacy-dashboard"),
    path("accounts/reservations/<int:pk>/", ModernReservationDetailView.as_view(), name="reservation-detail"),
    path("accounts/reservations/<int:pk>/edit/", ModernReservationUpdateView.as_view(), name="reservation-edit"),
    path("accounts/reservations/<int:pk>/cancel/", ModernReservationCancelView.as_view(), name="reservation-cancel"),
    path("legacy-accounts/reservations/<int:pk>/", RedirectView.as_view(pattern_name="bookings:reservation-detail", permanent=False), name="legacy-reservation-detail"),
    path("legacy-accounts/reservations/<int:pk>/edit/", RedirectView.as_view(pattern_name="bookings:reservation-edit", permanent=False), name="legacy-reservation-edit"),
    path("legacy-accounts/reservations/<int:pk>/cancel/", RedirectView.as_view(pattern_name="bookings:reservation-cancel", permanent=False), name="legacy-reservation-cancel"),
    path("stays/<slug:slug>/", ModernSiteView.as_view(), name="stay-detail"),
    path("legacy-stays/<slug:slug>/", RedirectView.as_view(pattern_name="bookings:stay-detail", permanent=False), name="legacy-stay-detail"),
    path("inquiries/", BookingInquiryCreateView.as_view(), name="inquiry-create"),
    path("invoices/<uuid:token>/", InvoicePrintView.as_view(), name="invoice-print"),
    path("deposits/checkout/", DamageDepositCheckoutView.as_view(), name="deposit-checkout"),
    path("deposits/success/", DamageDepositSuccessView.as_view(), name="deposit-success"),
    path("deposits/paypal/success/", PayPalDamageDepositSuccessView.as_view(), name="deposit-paypal-success"),
    path("deposits/paypal/cancel/", PayPalDamageDepositCancelView.as_view(), name="deposit-paypal-cancel"),
    path("payments/context/", ReservationPaymentContextAPIView.as_view(), name="reservation-payment-context"),
    path("payments/checkout/", ReservationPaymentCheckoutView.as_view(), name="reservation-payment-checkout"),
    path("payments/success/", ReservationPaymentSuccessView.as_view(), name="reservation-payment-success"),
    path(
        "payments/combined-checkout/<uuid:token>/",
        CombinedPaymentCheckoutView.as_view(),
        name="combined-payment-checkout",
    ),
    path("payments/combined/success/", CombinedPaymentSuccessView.as_view(), name="combined-payment-success"),
    path(
        "payments/confirmation/<uuid:token>/",
        PaymentConfirmationView.as_view(),
        name="payment-confirmation",
    ),
    path("donations/checkout/", DonationCheckoutView.as_view(), name="donation-checkout"),
    path("donations/success/", DonationSuccessView.as_view(), name="donation-success"),
    path("ops/dashboard/", ModernOpsDashboardView.as_view(), name="ops-dashboard"),
    path("ops/admin/", ModernOpsDashboardView.as_view(), name="ops-admin"),
    path("ops/legacy-dashboard/", RedirectView.as_view(pattern_name="bookings:ops-dashboard", permanent=False), name="ops-legacy-dashboard"),
    path("ops/reservations/", ModernOpsReservationsView.as_view(), name="ops-reservations"),
    path("ops/legacy-reservations/", RedirectView.as_view(pattern_name="bookings:ops-reservations", permanent=False), name="ops-legacy-reservations"),
    path("ops/reports/", ModernOpsReportsView.as_view(), name="ops-reports"),
    path("ops/legacy-reports/", RedirectView.as_view(pattern_name="bookings:ops-reports", permanent=False), name="ops-legacy-reports"),
    path("ops/customers/", ModernOpsCustomersView.as_view(), name="ops-customers"),
    path("ops/payments/", ModernOpsPaymentsView.as_view(), name="ops-payments"),
    path("ops/deposits/", ModernOpsDepositsView.as_view(), name="ops-deposits"),
    path("ops/agent/", ModernOpsAgentView.as_view(), name="ops-agent"),
    path("ops/maintenance/", ModernOpsMaintenanceView.as_view(), name="ops-maintenance"),
    path("ops/calendar/", ModernOpsCalendarView.as_view(), name="calendar-ops"),
    path("ops/stays/", ModernOpsStaysView.as_view(), name="ops-stays"),
    path("ops/settings/", ModernOpsDashboardView.as_view(), name="ops-settings"),
    path("ops/calendar/list/", ModernOpsCalendarView.as_view(), name="calendar-ops-list"),
    path("ops/calendar/rooms/", ModernOpsCalendarView.as_view(), name="calendar-ops-rooms"),
    path("ops/calendar/analytics/", ModernOpsCalendarView.as_view(), name="calendar-ops-analytics"),
    path("ops/oauth/", OAuthDiagnosticsView.as_view(), name="oauth-diagnostics"),
    path("stripe/webhook/", StripeWebhookView.as_view(), name="stripe-webhook"),
    path("api/agent/", AgentAPIView.as_view(), name="agent-api"),
    path("api/chatkit/session/", ChatKitSessionAPIView.as_view(), name="chatkit-session-api"),
    path("api/account/summary/", AccountSummaryAPIView.as_view(), name="account-summary-api"),
    path("api/site/summary/", PublicSiteSummaryAPIView.as_view(), name="site-summary-api"),
    path("api/ops/summary/", OpsSummaryAPIView.as_view(), name="ops-summary-api"),
    path("api/ops/reports/", OpsReportsAPIView.as_view(), name="ops-reports-api"),
    path("api/ops/reservations/", OpsReservationsAPIView.as_view(), name="ops-reservations-api"),
    path("api/ops/reservations/<int:pk>/status/", OpsReservationStatusAPIView.as_view(), name="ops-reservation-status-api"),
    path("api/ops/customers/", OpsCustomersAPIView.as_view(), name="ops-customers-api"),
    path("api/ops/deposits/", OpsDepositsAPIView.as_view(), name="ops-deposits-api"),
    path("api/ops/agent/", OpsAgentAPIView.as_view(), name="ops-agent-api"),
    path("api/ops/maintenance/", OpsMaintenanceAPIView.as_view(), name="ops-maintenance-api"),
    path("api/ops/maintenance/ai-description/draft/", OpsMaintenanceDraftAIDescriptionAPIView.as_view(), name="ops-maintenance-ai-description-draft-api"),
    path("api/ops/maintenance/<uuid:pk>/agent-payload/", OpsMaintenanceAgentPayloadAPIView.as_view(), name="ops-maintenance-agent-payload-api"),
    path("api/ops/maintenance/<uuid:pk>/ai-description/", OpsMaintenanceAIDescriptionAPIView.as_view(), name="ops-maintenance-ai-description-api"),
    path("api/ops/calendar/", OpsCalendarAPIView.as_view(), name="ops-calendar-api"),
    path("api/ops/calendar/blocks/", OpsCalendarBlockAPIView.as_view(), name="ops-calendar-blocks-api"),
    path("api/ops/calendar/prices/", OpsCalendarPriceAPIView.as_view(), name="ops-calendar-prices-api"),
]
