from rest_framework import permissions, viewsets, decorators, response, parsers
from .models import MaintenanceEvent
from .serializers import MaintenanceEventSerializer, MaintenanceInvoicePayloadSerializer


class IsAdminOrStaff(permissions.BasePermission):
    """Allow create/update only to staff or superusers; safe methods to authenticated users."""

    def has_permission(self, request, view):
        if request.method in permissions.SAFE_METHODS:
            return request.user and request.user.is_authenticated
        return request.user and (request.user.is_staff or request.user.is_superuser)


class MaintenanceEventViewSet(viewsets.ModelViewSet):
    """
    Controller layer (MVC) for MaintenanceEvent.

    Routes (auto-generated by DefaultRouter):
      GET    /api/maintenance/                       — list
      POST   /api/maintenance/                       — create
      GET    /api/maintenance/{id}/                  — retrieve
      PATCH  /api/maintenance/{id}/                  — partial update
      DELETE /api/maintenance/{id}/                  — destroy
      GET    /api/maintenance/{id}/invoice-payload/  — agent invoice JSON
    """

    queryset = (
        MaintenanceEvent.objects
        .select_related("property", "booking", "created_by")
        .prefetch_related("photos")
    )
    serializer_class = MaintenanceEventSerializer
    permission_classes = [IsAdminOrStaff]
    parser_classes = [parsers.MultiPartParser, parsers.FormParser, parsers.JSONParser]

    def get_queryset(self):
        qs = super().get_queryset()
        # Optional query-param filters
        property_id = self.request.query_params.get("property")
        status_filter = self.request.query_params.get("status")
        category = self.request.query_params.get("category")
        if property_id:
            qs = qs.filter(property_id=property_id)
        if status_filter:
            qs = qs.filter(status=status_filter)
        if category:
            qs = qs.filter(category=category)
        return qs

    @decorators.action(
        detail=True,
        methods=["get"],
        url_path="invoice-payload",
        permission_classes=[IsAdminOrStaff],
    )
    def invoice_payload(self, request, pk=None):
        """
        Returns the normalized JSON block that the billing/tax document agent expects.
        Guaranteed to include title, cost, time, and pictures.
        """
        event = self.get_object()
        payload = event.to_agent_payload()
        serializer = MaintenanceInvoicePayloadSerializer({"payload": payload})
        return response.Response(serializer.data)
