# Generated by Django 5.2.13 on 2026-04-29 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_damage_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bookableitem',
            name='image_alt',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='bookableitem',
            name='marketing_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookableitem',
            name='marketing_headline',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='bookableitem',
            name='rating_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='bookableitem',
            name='rating_checkin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='bookableitem',
            name='rating_cleanliness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='bookableitem',
            name='rating_communication',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='bookableitem',
            name='rating_location',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='bookableitem',
            name='rating_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='bookableitem',
            name='review_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CalendarFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airbnb_ical_url', models.URLField(blank=True, max_length=1000)),
                ('google_calendar_name', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_feed', to='bookings.bookableitem')),
            ],
            options={
                'ordering': ['item__name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(choices=[('new', 'New'), ('requires_configuration', 'Requires Stripe configuration'), ('checkout_created', 'Checkout created'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='new', max_length=32)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='bookings.missioncause')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=180)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_themes', to='bookings.bookableitem')),
            ],
            options={
                'ordering': ['item', 'sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='StayGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('alt_text', models.CharField(max_length=180)),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('is_demo', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='bookings.bookableitem')),
            ],
            options={
                'ordering': ['item', 'sort_order', 'id'],
            },
        ),
    ]
