# Generated by Django 5.2.13 on 2026-04-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_seed_booking_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('grant_staff_access', models.BooleanField(default=True)),
                ('grant_superuser_access', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'admin access',
                'verbose_name_plural': 'admin access',
                'ordering': ['name', 'email'],
            },
        ),
    ]
