# Generated by Django 5.2.13 on 2026-05-09 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_damagedeposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='marketing_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='marketing_consent_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='marketing_consent_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='marketing_consent_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('requested', 'Requested'), ('opted_in', 'Opted in'), ('opted_out', 'Opted out')], default='unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct booking'), ('airbnb', 'Airbnb'), ('social', 'Social login'), ('manual', 'Manual entry')], default='direct', max_length=24),
        ),
        migrations.CreateModel(
            name='AirbnbGuestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('listing_title', models.CharField(blank=True, max_length=240)),
                ('airbnb_listing_id', models.CharField(blank=True, max_length=40)),
                ('airbnb_thread_url', models.URLField(blank=True, max_length=600)),
                ('source_message_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('source_email_subject', models.CharField(blank=True, max_length=300)),
                ('source_email_timestamp', models.DateTimeField(blank=True, null=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('guests', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message_excerpt', models.TextField(blank=True)),
                ('feedback_summary', models.TextField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('permission_notes', models.TextField(blank=True, help_text='Track how we can contact this Airbnb guest and whether they gave permission for future offers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airbnb_guest_records', to='bookings.customerprofile')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airbnb_guest_records', to='bookings.bookableitem')),
            ],
            options={
                'verbose_name': 'Airbnb guest record',
                'verbose_name_plural': 'Airbnb guest records',
                'ordering': ['-check_in', 'guest_name'],
            },
        ),
    ]
