# Generated by Django 5.2.13 on 2026-05-10 01:52

import django.db.models.deletion
from django.db import migrations, models


def copy_airbnb_feedback(apps, schema_editor):
    AirbnbGuestRecord = apps.get_model("bookings", "AirbnbGuestRecord")
    CustomerFeedback = apps.get_model("bookings", "CustomerFeedback")

    for record in (
        AirbnbGuestRecord.objects.select_related("customer_profile", "item")
        .all()
        .iterator()
    ):
        feedback_text = (record.feedback_summary or record.message_excerpt or "").strip()
        if not feedback_text and record.rating is None:
            continue

        profile = record.customer_profile
        CustomerFeedback.objects.update_or_create(
            airbnb_guest_record_id=record.pk,
            defaults={
                "customer_profile_id": profile.pk if profile else None,
                "item_id": record.item_id,
                "source": "airbnb",
                "source_label": "Airbnb message import",
                "source_url": record.airbnb_thread_url,
                "guest_name": record.guest_name,
                "email": record.email or (profile.email if profile else ""),
                "phone": record.phone or (profile.phone if profile else ""),
                "rating": record.rating,
                "feedback_text": feedback_text or "Airbnb rating captured without written feedback.",
                "feedback_summary": record.feedback_summary,
                "permission_notes": record.permission_notes,
            },
        )


def remove_airbnb_feedback(apps, schema_editor):
    CustomerFeedback = apps.get_model("bookings", "CustomerFeedback")
    CustomerFeedback.objects.filter(source="airbnb", airbnb_guest_record__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_customerprofile_marketing_consent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('direct', 'Direct booking'), ('airbnb', 'Airbnb'), ('social', 'Social login'), ('manual', 'Manual entry')], default='direct', max_length=24)),
                ('source_label', models.CharField(default='Website feedback', max_length=120)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('guest_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('feedback_text', models.TextField()),
                ('feedback_summary', models.TextField(blank=True)),
                ('permission_notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Only publish exact feedback when we have permission to display it publicly.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airbnb_guest_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_feedback', to='bookings.airbnbguestrecord')),
                ('customer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='bookings.customerprofile')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_feedback_entries', to='bookings.bookableitem')),
            ],
            options={
                'verbose_name': 'customer feedback',
                'verbose_name_plural': 'customer feedback',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(copy_airbnb_feedback, remove_airbnb_feedback),
    ]
