# Generated by Django 5.2.13 on 2026-05-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0015_customerfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentKnowledgeSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(max_length=160),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("inline", "Inline text"),
                            ("repo_file", "Repo file"),
                            ("url", "Public URL or GitHub link"),
                        ],
                        default="inline",
                        max_length=24,
                    ),
                ),
                (
                    "source_value",
                    models.CharField(
                        blank=True,
                        help_text="Repo-relative file path or public URL, depending on source type.",
                        max_length=1000,
                    ),
                ),
                (
                    "body",
                    models.TextField(blank=True, help_text="Paste guest-facing text here for inline sources."),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "agent knowledge source",
                "verbose_name_plural": "agent knowledge sources",
                "ordering": ["sort_order", "title"],
            },
        ),
    ]