# Generated by Django 5.2.15 on 2026-06-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_agentfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='MLADIS LLC', max_length=80),
        ),
    ]
