# Generated by Codex on 2026-06-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0020_alter_sitesettings_site_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconversation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="agent_question_limit",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Maximum public agent questions per signed-in user. Use 0 for unlimited.",
            ),
        ),
    ]
