# Generated by Django 5.2.13 on 2026-06-07 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_sitesettings_request_notification_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPaymentHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('payment_provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], default='stripe', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('requires_configuration', 'Requires payment configuration'), ('checkout_created', 'Checkout created'), ('requires_capture', 'Authorized'), ('captured', 'Captured'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='new', max_length=32)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('capture_after', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_holds', to='bookings.bookinginquiry')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_holds', to='bookings.bookableitem')),
            ],
            options={
                'verbose_name': 'reservation payment hold',
                'verbose_name_plural': 'reservation payment holds',
                'ordering': ['-created_at'],
            },
        ),
    ]
