# Generated by Django 5.2.13 on 2026-06-07 19:28

import bookings.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_reservationpaymenthold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('work_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('repair', 'Repair'), ('replacement', 'Replacement'), ('inspection', 'Inspection'), ('supplies', 'Supplies'), ('penalty', 'Penalty'), ('other', 'Other')], default='cleaning', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('logged', 'Logged'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('documented', 'Documented'), ('billed', 'Billed'), ('archived', 'Archived')], default='completed', max_length=24)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_currency', models.CharField(default='USD', max_length=3)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('timezone_name', models.CharField(default='America/Santo_Domingo', max_length=64)),
                ('vendor_name', models.CharField(blank=True, max_length=160)),
                ('vendor_contact', models.CharField(blank=True, max_length=160)),
                ('invoice_number', models.CharField(blank=True, max_length=80)),
                ('proof_of_payment_ref', models.CharField(blank=True, max_length=180)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('reimbursed', 'Reimbursed'), ('disputed', 'Disputed')], default='pending', max_length=24)),
                ('tax_category_code', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenance_events', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_events', to='bookings.bookinginquiry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_events', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_events', to='bookings.bookableitem')),
            ],
            options={
                'verbose_name': 'maintenance event',
                'verbose_name_plural': 'maintenance events',
                'ordering': ['-reported_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=bookings.models.maintenance_upload_path)),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bookings.maintenanceevent')),
            ],
            options={
                'verbose_name': 'maintenance photo',
                'verbose_name_plural': 'maintenance photos',
                'ordering': ['event', 'sort_order', 'uploaded_at'],
            },
        ),
    ]
