# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0024_maintenanceevent_maintenancephoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceevent",
            name="ai_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="maintenanceevent",
            name="ai_description_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenanceevent",
            name="ai_description_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="maintenanceevent",
            name="ai_description_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="maintenanceevent",
            name="use_ai_description",
            field=models.BooleanField(default=False),
        ),
    ]
